model_name: "lgbr"
hyperparameters:
  n_estimators: [100, 1000]
  learning_rate: [0.01, 0.1]
  num_leaves: [20, 300]
  max_depth: [3, 20]
  min_child_samples: [5, 100]
  subsample: [0.5, 1.0]
  colsample_bytree: [0.5, 1.0]
  reg_alpha: [0.0, 1.0]
  reg_lambda: [0.0, 1.0]
